/********************************************************************
* Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TLorentzVector.h"
#include "Math/LorentzVector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_ROOT;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DictLN_TLorentzVector;
extern G__linked_taginfo G__DictLN_ROOTcLcLMath;
extern G__linked_taginfo G__DictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_ROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgR;
extern G__linked_taginfo G__DictLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgR;
extern G__linked_taginfo G__DictLN_ROOTcLcLMathcLcLCartesian3DlEfloatgR;
extern G__linked_taginfo G__DictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEfloatgRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<TLorentzVector,allocator<TLorentzVector> > G__vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR;
typedef ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > G__ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgR;
typedef vector<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> >,allocator<ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiM4D<float> > > > G__vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPtEtaPhiM4DlEfloatgRsPgRsPgRsPgR;
